apiVersion: v1
kind: Service
metadata:
  name: python-web-fe-deploy
  namespace: python-web-fe
  labels:
    app.kubernetes.io/name: python-web-fe-deploy
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: python-web-fe-deploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000